hew:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 0.25, i: 0.0, d: 0.0}
  # Position Controllers ---------------------------------------
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 0.01, i: 0.0, d: 0.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: Front_Wheel_cont
    pid: {p: 0.5, i: 0.0, d: 0.0}